name: Deploy to Namecheap

on:
  push:
    branches: [ master ]
    paths: [ 'frontend/src/**', 'package.json', 'frontend/src/contract-config.js' ]  # Deploy when src changes or version bumps

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Clean install dependencies
      run: |
        cd frontend
        rm -rf node_modules package-lock.json
        npm install
        npm install @rollup/rollup-linux-x64-gnu --save-dev
      
    - name: Build frontend
      run: cd frontend && npm run build
      
    - name: Validate pre-built files exist
      run: |
        echo "Checking for pre-built files..."
        if [ ! -d "frontend/dist" ]; then
          echo "❌ Error: frontend/dist directory not found!"
          exit 1
        fi
        ls -la frontend/dist/
        echo "✅ Pre-built files found and ready for deployment"
        
    - name: Deploy to FTP
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/dist/
        server-dir: /
        exclude: |
          **/.DS_Store
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/.env.*
          **/README.md
          **/package*.json
          **/tsconfig.json
          **/vite.config.js
          **/src/**
          **/public/deploy/**
        log-level: verbose
        timeout: 600000
        dry-run: false
        dangerous-clean-slate: false
